### ISSUE TITLE
Prepare a Windows .exe from stable production version

### ISSUE THREAD

**Issue by leowmjw** [leowmjw/playground-python#5]
Pre-req on #4 being completed first

Use something like PyWin when get back Windows laptop

**Comment by leowmjw** [comment]
Tested out on cx_Freeze; which seems to be the more modern choice.

Even so, cannot cross-compile to Windows from OSX; so will need to retry again on a Windows box.

The needed command to compile standalone:

```
leow$ ~/PyOGR/bin/cxfreeze  --target-dir=/tmp/OGR/ --include-modules=json ~/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/ogr.py
```

If encounter the below issue:

```
leow$ ./ogr 
Traceback (most recent call last):
  File "/Users/leow/PyOGR/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "./ogr.py", line 1, in <module>
  File "./excel.py", line 9, in <module>
  File "/Users/leow/PyOGR/lib/python2.7/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/leow/PyOGR/lib/python2.7/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  File "ExtensionLoader_fiona_ogrext.py", line 22, in <module>
  File "ExtensionLoader_fiona_ogrext.py", line 14, in __bootstrap__
ImportError: dlopen(/private/tmp/OGR/fiona.ogrext.so, 2): Library not loaded: @loader_path/libproj.0.dylib
  Referenced from: /private/tmp/OGR/.dylibs/libgdal.1.dylib
  Reason: image not found
```

it means the dynamic libs was not placed in correct location; to solve, setup the necessary files and dynamic libs at the correct location:

```
leow$ cp -a ~/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/source .
leow$ cp -a ~/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/template .
leow$ mkdir .dylibs
leow$ mv *.dylib .dylibs/.

```

Finally, confirm it works as expected:

```
leow$ ./ogr 
Sinar Project OGR Attribute Tables Processing!!!
{'geometry': 'Polygon',
 'properties': OrderedDict([(u'NAME', 'str:12'), (u'NAMA_DM', 'str:128'), (u'PAR_LAMA', 'str:5'), (u'DUN_LAMA', 'str:5'), (u'DM_LAMA', 'str:5'), (u'PENGUNDI', 'int:6'), (u'KODPAR', 'str:5'), (u'PAR_BARU', 'str:128'), (u'KODDUN', 'str:5'), (u'DUN_BARU', 'str:128'), (u'KODDM', 'str:5'), (u'DM_BARU', 'str:128'), (u'PENGUNDI_B', 'int:6')])}
in Extract Feature Map ...
in Extract Data ...
in Find DM Match of ED Data ...
Size of ECMAP at start is 852 
MSG: KGSEBEMBAN
MSG: MELABAN
MSG: SAGENG
MSG: SEKENDU
MSG: ENSENGAI
MSG: TEGELAM
MSG: KENIONG
MSG: TUNGKAH
MSG: SENYAWAN
MSG: BAJAU
MSG: KRANGAN
MSG: NANGALEPA
MSG: INDAH
MSG: NIBONG
MSG: ANNAU
MSG: NANGAPERARAN
MSG: LONGBUSANG
MSG: LONGBANGAN
MSG: LONGSEMUTUT
MSG: DESADAMAI
MSG: BATULIMA
MSG: AIRPORT
MSG: TUKAU
MSG: RAMD
MSG: LUAK
MSG: LONGTERU
MSG: LONGPELUAN
Size of ECMAP at end is 1 
{u'KAMPUNGSEBEMBAN': ['58']}
Write to Shapefile!!
>>>>>>>>>>>>>>>>>>>>>>>>>
OrderedDict([(u'NAME', u'215/62/06'), (u'NAMA_DM', u'BANGKIT'), (u'PAR_LAMA', u'215'), (u'DUN_LAMA', u'55'), (u'DM_LAMA', u'06'), (u'PENGUNDI', 1397), (u'KODPAR', u'215'), (u'PAR_BARU', u'KAPIT'), (u'KODDUN', u'62'), (u'DUN_BARU', u'Katibas'), (u'KODDM', u'06'), (u'DM_BARU', u'BANGKIT'), (u'PENGUNDI_B', u'1458'), ('NAMA_LAMA', u'215/55/06')])
>>>>>>>>>>>>>>>>>>>>>>>>>
OrderedDict([(u'NAME', u'204/37/35'), (u'NAMA_DM', u'BANGKIT'), (u'PAR_LAMA', u'204'), (u'DUN_LAMA', u'32'), (u'DM_LAMA', u'34'), (u'PENGUNDI', 101), (u'KODPAR', u'204'), (u'PAR_BARU', u'BETONG'), (u'KODDUN', u'37'), (u'DUN_BARU', u'Bukit Saban'), (u'KODDM', u'35'), (u'DM_BARU', u'BANGKIT'), (u'PENGUNDI_B', u'101'), ('NAMA_LAMA', u'204/32/34')])
```

Correct output:

```
leow$ ls results/
new-Sarawak-wip.cpg new-Sarawak-wip.prj new-Sarawak-wip.shx new-Sarawak.dbf     new-Sarawak.shp
new-Sarawak-wip.dbf new-Sarawak-wip.shp new-Sarawak.cpg     new-Sarawak.prj     new-Sarawak.shx
```

**Comment by leowmjw** [comment]
Completed a build that can run (other than the blocking SegFault below).  A standalone .exe can be run and distributed from the items in dist folder.  Compressed tarball of binary + libs come up to 13MB!

Needed to fix the cxfreeze script as such to work on a VirtualEnv:

```
$ diff ~/PyOGR/Scripts/cxfreeze ~/PyOGR/Scripts/my-cxfreeze
1c1
< #!c:\python\32-bit\2.7\python.exe
---
> #!/c/Users/leow/PyOGR/Scripts/python
```

Then execute below for creating the binaries:

```
 ~/PyOGR/Scripts/my-cxfreeze --target-dir=./dist/ --include-modules=json ./ogr.py 
```

Final Output until hit Roadblock:

```
$ pwd
/c/Users/leow/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/dist
(PyOGR)
leow@LE5510-0001 MINGW32 ~/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/dist (origin/develop)
$ ls
_ctypes.pyd*   fiona._drivers.pyd*   geos_c.dll*       results/
_hashlib.pyd*  fiona._err.pyd*       ogr.exe*          source/
_socket.pyd*   fiona._geometry.pyd*  osgeo._gdal.pyd*  template/
_ssl.pyd*      fiona.ogrext.pyd*     python27.dll*     unicodedata.pyd*
bz2.pyd*       gdal111.dll*          README.md
(PyOGR)
leow@LE5510-0001 MINGW32 ~/Desktop/PROJECTS/SINARPROJECT/playground-python/ogr/dist (origin/develop)
$ ./ogr.exe
Sinar Project OGR Attribute Tables Processing!!!
{'geometry': 'Polygon',
 'properties': OrderedDict([(u'NAME', 'str:12'), (u'NAMA_DM', 'str:128'), (u'PAR_LAMA', 'str:5'), (u'DUN_LAMA', 'str:5'), (u'DM_LAMA', 'str:5'), (u'PENGUNDI', 'int:6'), (u'KODPAR', 'str:5'), (u'PAR_BARU', 'str:128'), (u'KODDUN', 'str:5'), (u'DUN_BARU', 'str:128'), (u'KODDM', 'str:5'), (u'DM_BARU', 'str:128'), (u'PENGUNDI_B', 'int:6')])}
in Extract Feature Map ...
in Extract Data ...
in Find DM Match of ED Data ...
Size of ECMAP at start is 852
MSG: KGSEBEMBAN
MSG: MELABAN
MSG: SAGENG
MSG: SEKENDU
MSG: ENSENGAI
MSG: TEGELAM
MSG: KENIONG
MSG: TUNGKAH
MSG: SENYAWAN
MSG: BAJAU
MSG: KRANGAN
MSG: NANGALEPA
MSG: INDAH
MSG: NIBONG
MSG: ANNAU
MSG: NANGAPERARAN
MSG: LONGBUSANG
MSG: LONGBANGAN
MSG: LONGSEMUTUT
MSG: DESADAMAI
MSG: BATULIMA
MSG: AIRPORT
MSG: TUKAU
MSG: RAMD
MSG: LUAK
MSG: LONGTERU
MSG: LONGPELUAN
Size of ECMAP at end is 1
{u'KAMPUNGSEBEMBAN': ['58']}
Write to Shapefile!!
Segmentation fault
```

Blocking item is unlike in OSX, the code causes SegFault which has been reported to the author of FIona lib:
https://github.com/Toblerity/Fiona/issues/303

**Comment by leowmjw** [comment]
Able to figure out that it is due to the Unicode character in the field DUN_BARU causes the segfault; why is still unknown.  If correct the source CSV, it works on PyCharm.

However, was not successful in packaging the exe; also tried with py2exe but also failed.  Giving up for now; possibly will go with the gRPC method.
